language: objective-c
script:
    - cd NBUStatProject
    - pod install 
    - xcodebuild test -workspace "FinStat Ukraine.xcworkspace" -scheme "FinStat Ukraine - QA" -sdk iphonesimulator -destination 'platform=iOS,OS=10.1,name=iPhone X' ONLY_ACTIVE_ARCH=NO
osx_image: xcode9.2
