# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# ignore all warnings from all pods
inhibit_all_warnings!
target 'FinStat Ukraine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.2'
  pod 'Charts'
  pod 'NTMonthYearPicker'
  pod 'KJExpandableTableTree'
  # Pods for NBUStat

#target 'NBUStatTests' do
#    inherit! :search_paths
    # Pods for testing
    #  end

# target 'NBUStatUITests' do
#inherit! :search_paths
    # Pods for testing
    #  end

end

