# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FinStat Ukraine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.2'
  pod 'Charts'
  # Pods for NBUStat

#target 'NBUStatTests' do
#    inherit! :search_paths
    # Pods for testing
    #  end

# target 'NBUStatUITests' do
#inherit! :search_paths
    # Pods for testing
    #  end

end

